<?xml version="1.0" encoding="utf-8"?>
<Database Name="QLSV" EntityNamespace="QUANLYSV" ContextNamespace="QUANLYSV" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.LopHoc" Member="LopHoc">
    <Type Name="LopHoc">
      <Column Name="MaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="FK_SinhVien_LopHoc" Member="SinhVien" ThisKey="MaLop" OtherKey="MaLop" Type="SinhVien" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhVien">
    <Type Name="SinhVien">
      <Column Name="MaSV" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="FK_SinhVien_LopHoc" Member="LopHoc" ThisKey="MaLop" OtherKey="MaLop" Type="LopHoc" IsForeignKey="true" />
    </Type>
  </Table>
</Database>